### PR TITLE
Modified to only display available locales in dashboard

### PR DESCRIPTION
**Pull request by Kulgar**
Here is my pull request for issue #41

I'm not sure if the modification in i18n_backend.rb is needed or not... You tell me :wink:

### CODE REVIEW

**Comment by rafaltrojanowski** [comment]
It may be important:

I set config.i18n.available_locales = nil in my rails app (i18n (0.7.0))

And…

Loading development environment (Rails 4.1.9)
2.2.0 :001 > I18n.available_locales
 => [:en]
2.2.0 :002 > ::Rails.configuration.i18n.available_locales
 => nil

**Comment by mlitwiniuk** [comment]
cc @Bonias

**Comment by Bonias** [comment]
Referring to the code from this pull request.

    #Lit::Locale
    scope :availables, proc { where(:locale => I18n.available_locales.map(&:to_s))}
      
    # Lit::I18nBackend
    def available_locales
        Lit::Locale.ordered.availables.visible.map{|l| l.locale.to_sym }
    end

Scope 'availables' uses `I18n.available_locales` which uses `I18.backend.available_locales` (in case when user does not define `config.i18n.available_locales`), and now `available_locales` from Lit::I18nBackend uses `availables` scope. This creates endless loop:

    $ rails c
    Loading development environment (Rails 4.2.0)
    Warning: The plugin 'doc' was not found! (no gem found)
    [1] pry(main)> Lit::Locale.ordered.availables
    SystemStackError: stack level too deep
    from /home/bonias/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.0/lib/active_record/scoping.rb:68:in `value_for'

Plus this pull request is old and should be rebased. Lit::I18nBackend#available_locales from master looks little different at the moment

--
Referring to the feature idea.

User can hide/show locales, and only this not hidden are shown in dashboard. We could check if ::Rails.configuration.i18n.available_locales is set and if actual locale exists in ::Rails.configuration.i18n.available_locales when we creating new Lit::Locale and if it does create locale with `is_hidden` flag set to `false` and `true` otherwise.

--
Referring to `I18n.available_locales` returning array when `Rails.configuration.i18n.available_locales` is nil.

Yes, `I18n.available_locales` cannot return `nil` unless `I18n.backend.available_locales` does return `nil` and I think none of `I18n.backend.available_locales` should return different object then `Array`.  `I18n::Backend::Simple` and `Lit::I18nBackend` does return `Array`.

**Comment by rafaltrojanowski** [comment]
@Bonias I really appreciate your explanation!

**Comment by Kulgar** [comment]
@Bonias @rafaltrojanowski: Yes, I'm really sorry but I really did not have time to rework my pull request yet... You can close it if you want, I'll re-open one when I'll have the time to. 

Thanks! :smile: 
Kulgar.

**Pull request closed without merging**
